[colors]
background = "#15140c"
foreground = "#e7e2d5"
cursor_bg = "#e7e2d5"
cursor_border = "#e7e2d5"
cursor_fg = "#cbc7b5"
selection_bg = "#cdc7a3"
selection_fg = "#343117"

split = "#cdc7a3"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8",
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF",
]
